swagger:
  api:
    title: LDAP JWT Authentication Service
    description: Backend service for authentication, jwt token generation and revokation
    version: 1.0-SNAPSHOT
    controller:
      basepackage: pl.ee.authentication.infrastructure.rest
app:
  jwtExpirationInMs: 3600000
  jwtSecret: HyperSecretPasswordMadeByKubehe
  ldap:
    url: ldap://localhost:12345
    base-dn: dc=ee,dc=pl

server:
  port: 8089
  servlet:
    context-path: /api/v1.0

spring:
  ldap:
    embedded:
      base-dn: dc=ee,dc=pl
      ldif: classpath:/ldap/ad.ldif
      port: 12345
      validation:
        enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5433/authentication
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    locations: classpath:/authentication-db/migration
    enabled: true
debug: true
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework: ERROR
    pl.ee.external: DEBUG
