version: '3.0'

services:

  queue-db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: queue
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
    ports:
      - 5432:5432

  authentication-db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: authentication
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
    ports:
      - 5433:5432

  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "queue"
      RABBITMQ_DEFAULT_PASS: "queue"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 15672:15672
      - 5672:5672
    expose:
      - 15672
      - 5672
    tty: true