version: '3.0'

services:

  queue-db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: queue
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
    ports:
      - 5432:5432

  authentication-db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: authentication
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
    ports:
      - 5433:5432