swagger:
  api:
    title: Queue to Deanery
    description: Backend service for students
    version: 1.0-SNAPSHOT
    controller:
      basepackage: pl.ee.external.infrastructure.rest
app:
  authenticationUri: http://localhost:8089/api/v1.0

server:
  port: 8080
  servlet:
    context-path: /api/v1.0
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/queue
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    enabled: true
    locations: classpath:/queue-db/migration,classpath:/db/test-dml
  mvc:
    throw-exception-if-no-handler-found: false

exception:
  not-found:
    pl: Nie znaleziono zasobu {}
    en: Entity {} not found
debug: true
